name: Test Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy

    - name: Install package
      run: |
        pip install .

    - name: Test OpenCV import
      run: |
        python -c "import cv2; print(f'OpenCV version: {cv2.__version__}')"
        python -c "import cv2; print(f'CUDA devices: {cv2.cuda.getCudaEnabledDeviceCount()}')"

    - name: Run basic tests
      run: |
        python -c "
        import cv2
        import numpy as np
        
        # Test basic functionality
        img = np.zeros((100, 100, 3), dtype=np.uint8)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        assert gray.shape == (100, 100)
        print('Basic OpenCV functionality works')
        
        # Test contrib modules
        try:
            import cv2.aruco
            print('ARUCO module available')
        except:
            print('ARUCO module not available')
        
        print('All tests passed')
        "